apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: 6bdd9402-8c70-4732-a376-995c13de5157
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: post-close-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /ticket/post_user_account_close
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /ticket/post_user_account_close
