apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: post-close-route
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: post-close-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /support/post-ticket-user-account-close
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /support/post-ticket-user-account-close
