include:
- ./func/*
kind: ArchiveUploadSpec
name: func-45MG

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: post-close-fn-a8969eab-6116-4e8c-b5cb-386290f3e518
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: post-close-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-45MG
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-07-12T18:52:59Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: post-close-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 1
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 80
    StrategyType: execution
  concurrency: 500
  environment:
    name: post-close-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.post_user_ticket
    packageref:
      name: post-close-fn-a8969eab-6116-4e8c-b5cb-386290f3e518
      namespace: default
  requestsPerPod: 1
  resources: {}
