include:
- ./func/*
kind: ArchiveUploadSpec
name: func-xiRr

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: post-close-fn-1cf021b0-965f-41d6-8705-daf9f5b6cdab
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: post-close-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-xiRr
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-07-12T18:47:16Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: post-close-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 6
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 80
    StrategyType: execution
  concurrency: 500
  environment:
    name: post-close-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.post_user_ticket
    packageref:
      name: post-close-fn-1cf021b0-965f-41d6-8705-daf9f5b6cdab
      namespace: default
  requestsPerPod: 1
  resources: {}
