apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: 36a5985a-7c2e-4635-b78d-63537e2ee21d
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: post-close-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /ticket/post_user_account_close
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /ticket/post_user_account_close
